{
 "title": "Kubernetes Lab - Logs",
 "tags": [
  "kubernetes",
  "loki",
  "fluent-bit"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Logs del namespace test",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"fluent-bit\"}"
    }
   ]
  },
  {
   "title": "Logs de Node Web",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"fluent-bit\",namespace=\"test\",pod=~\"node-web-.*\"}"
    }
   ]
  },
  {
   "title": "Logs de PostgreSQL",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"fluent-bit\",namespace=\"test\",pod=~\"postgres-.*\"}"
    }
   ]
  }
 ]
}