# Etapa 1: Usamos alpine solo para preparar los archivos
FROM alpine:3.20 AS build
WORKDIR /site
COPY index.html .

# Etapa 2: Usamos Nginx para servir la pagina web
FROM nginx:1.27-alpine AS runtime

# Borramos la pagina por defecto que trae Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copiamos nuestro index.html de la etapa 1 hacia la carpeta de Nginx
COPY --from=build /site/index.html /usr/share/nginx/html/index.html

# Le decimos que escuche por el puerto 80
EXPOSE 80

# Encendemos el servidor para que no se apague el contenedor
CMD ["nginx", "-g", "daemon off;"]