apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgress
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef: 
            name: db-secret
          